export const kalkuramaSource = Object.freeze({
  repository: "cemfirat/kalkurama",
  commit: "2bd658c65020984fe2583161ae8cceeae583f618",
  inspectedAt: "2026-10-08",
  inspectedPaths: [
    "docs/product/product-definition.md",
    "docs/product/billings-like-ux.md",
    "docs/product/estimate-workflow.md",
    "docs/product/invoice-workflow.md",
    "docs/product/payment-workflow.md",
    "templates/base.html.twig",
    "templates/shell/_sidebar.html.twig",
    "templates/shell/_sidebar_customer_group.html.twig",
    "templates/customer/show.html.twig",
    "templates/customer/_running_timer.html.twig",
    "templates/home/index.html.twig",
    "templates/project/show.html.twig",
    "templates/estimate/index.html.twig",
    "templates/estimate/show.html.twig",
    "templates/invoice/index.html.twig",
    "templates/invoice/show.html.twig",
    "templates/payment/index.html.twig",
    "templates/credit_note/index.html.twig",
    "templates/service/index.html.twig",
    "templates/work/index.html.twig",
    "templates/time/index.html.twig",
    "templates/settings/commercial.html.twig",
    "assets/controllers/project_list_controller.js",
    "assets/controllers/timer_controller.js",
    "assets/styles/app.css",
    "config/packages/asset_mapper.yaml",
    "importmap.php"
  ]
});
